crypto = [
    "Bitcoin",
    "Ethereum",
    "Binance Coin",
    "Cardano",
    "XRP",
    "Dogecoin",
    "Polkadot",
    "Uniswap",
    "Chainlink",
    "Litecoin",
    "Bitcoin Cash",
    "Stellar",
    "Polygon",
    "VeChain",
    "Filecoin",
    "Solana",
    "TRON",
    "EOS",
    "Cosmos",
    "Algorand",
    "Tezos",
    "Dash",
    "Zcash",
    "THETA",
    "Aave",
    "Compound",
    "Maker",
    "SushiSwap",
    "Yearn.finance",
    "Ren",
    "1inch",
    "Chiliz",
    "Decentraland",
    "The Graph",
    "Enjin Coin",
    "Basic Attention Token",
    "Hedera Hashgraph",
    "Celsius",
    "Celo",
    "Flow",
    "Nexo",
    "Harmony",
    "Curve DAO Token",
    "Swipe",
    "PancakeSwap",
    "Axie Infinity",
    "Dai",
    "Avalanche",
    "Kusama",
    "Fantom",
    "Serum",
    "RENBTC",
    "Ocean Protocol",
    "SKALE Network",
    "The Sandbox",
    "Golem",
    "IoTeX",
    "Quant",
    "Polymath",
    "UTRUST",
    "Ravencoin",
    "NKN",
    "OceanEX Token",
    "Audius",
    "StormX",
    "Harvest Finance",
    "Reef Finance",
    "Energy Web Token",
    "DODO",
    "Raydium",
    "Injective Protocol",
    "Numeraire",
    "Nervos Network",
    "Band Protocol",
    "Balancer",
    "COTI",
    "Ankr",
    "district0x",
    "Cartesi",
    "FEG Token",
    "Trust Wallet Token",
    "Polkastarter",
    "BakeryToken",
    "Everipedia",
    "Frax",
    "Render Token",
    "Mirror Protocol",
    "Arweave",
    "Kava.io"
]