economicTerms = [
    "Cryptocurrency",
    "Stocks",
    "Bonds",
    "Commodities",
    "Foreign exchange (Forex)",
    "Futures",
    "Options",
    "Initial public offering (IPO)",
    "Mutual funds",
    "Exchange-traded funds (ETFs)",
    "Real estate investment trusts (REITs)",
    "Hedge funds",
    "Private equity",
    "Venture capital",
    "Mergers and acquisitions (M&A)",
    "Derivatives",
    "Annuities",
    "Retirement accounts (e.g., 401(k), IRA)",
    "Risk management",
    "Asset allocation",
    "Capital gains tax",
    "Dividends",
    "Capital markets",
    "Investment banking",
    "Corporate finance",
    "Financial analysis",
    "Financial modeling",
    "Financial planning",
    "Credit ratings",
    "Economic indicators",
    "Gross Domestic Product (GDP)",
    "Consumer Price Index (CPI)",
    "Inflation",
    "Unemployment rate",
    "Interest rates",
    "Federal Reserve",
    "Central bank",
    "Monetary policy",
    "Fiscal policy",
    "Budget deficit",
    "Trade deficit",
    "Balance of payments",
    "Tariffs",
    "Free trade",
    "Globalization",
    "Supply chain",
    "Logistics",
    "E-commerce",
    "Brick and mortar",
    "Marketing",
    "Advertising",
    "Sales",
    "Customer relationship management (CRM)",
    "Market research",
    "Brand management",
    "Product development",
    "Supply and demand",
    "Price elasticity",
    "Marketing mix",
    "SWOT analysis",
    "Porter's Five Forces",
    "Business cycle",
    "Recession",
    "Depression",
    "Boom",
    "Bubble",
    "Financial crisis",
    "Black Swan event",
    "Emerging markets",
    "Developed markets",
    "Sustainability",
    "Corporate social responsibility (CSR)",
    "Environmental, social, and governance (ESG)",
    "Fair trade",
    "Labor standards",
    "Human rights",
    "Ethical investing",
    "Impact investing",
    "Philanthropy",
    "Nonprofit",
    "Social enterprise",
    "Microfinance",
    "Crowdfunding",
    "Angel investing",
    "Seed funding",
    "Series A funding",
    "IPO",
    "Secondary market",
    "Penny stocks",
    "Blue chip stocks",
    "Dividend stocks",
    "Growth stocks",
    "Value stocks",
    "Index funds",
    "Bond funds",
    "High-yield savings accounts",
    "CDs",
    "Money market accounts",
    "Brokerage accounts",
    "Robo-advisors",
    "Financial advisors",
    "Retirement planning",
    "Estate planning",
    "Tax planning",
    "Insurance",
    "Life insurance",
    "Health insurance",
    "Disability insurance",
    "Long-term care insurance",
    "Auto insurance",
    "Homeowners insurance",
    "Liability insurance",
    "Umbrella insurance",
    "Travel insurance",
    "Pet insurance",
    "Legal services",
    "Accounting services",
    "Tax preparation",
    "Bookkeeping",
    "Payroll services",
    "Virtual assistants",
    "Project management",
    "Time tracking",
    "Invoicing"
]