stocks = [
    "Apple Inc.",
    "Microsoft Corporation",
    "Amazon.com, Inc.",
    "Alphabet Inc.",
    "Tesla, Inc.",
    "Facebook, Inc.",
    "NVIDIA Corporation",
    "Visa Inc.",
    "JPMorgan Chase & Co.",
    "Berkshire Hathaway Inc.",
    "Johnson & Johnson",
    "Procter & Gamble Company",
    "Mastercard Incorporated",
    "UnitedHealth Group Incorporated",
    "Walmart Inc.",
    "The Home Depot, Inc.",
    "PayPal Holdings, Inc.",
    "Intel Corporation",
    "Verizon Communications Inc.",
    "The Coca-Cola Company",
    "Adobe Inc.",
    "Netflix, Inc.",
    "Abbott Laboratories",
    "Cisco Systems, Inc.",
    "Pfizer Inc.",
    "Honeywell International Inc.",
    "Broadcom Inc.",
    "Salesforce.com, Inc.",
    "AbbVie Inc.",
    "Caterpillar Inc.",
    "3M Company",
    "Chevron Corporation",
    "Exxon Mobil Corporation",
    "McDonald's Corporation",
    "The Walt Disney Company",
    "The Goldman Sachs Group, Inc.",
    "The Boeing Company",
    "Nike, Inc.",
    "American Express Company",
    "The Procter & Gamble Company",
    "Johnson Controls International plc",
    "The Travelers Companies, Inc.",
    "The J.M. Smucker Company",
    "International Business Machines Corporation",
    "The Procter & Gamble Company",
    "Honeywell International Inc.",
    "Merck & Co., Inc.",
    "The Home Depot, Inc.",
    "Cisco Systems, Inc.",
    "Johnson & Johnson",
    "The Walt Disney Company",
    "JPMorgan Chase & Co.",
    "Microsoft Corporation",
    "Visa Inc.",
    "Apple Inc.",
    "The Goldman Sachs Group, Inc.",
    "UnitedHealth Group Incorporated",
    "Amazon.com, Inc.",
    "The Boeing Company",
    "The Coca-Cola Company",
    "Intel Corporation",
    "The Walt Disney Company",
    "The Home Depot, Inc.",
    "The Procter & Gamble Company",
    "JPMorgan Chase & Co.",
    "3M Company",
    "Caterpillar Inc.",
    "Cisco Systems, Inc.",
    "The Goldman Sachs Group, Inc.",
    "Johnson & Johnson",
    "McDonald's Corporation"
]